version: 1
formatters:
    default:
        format: "%(asctime)s|%(levelname)s|%(name)s: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: default
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: default
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 1
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: default
        filename: error.log
        maxBytes: 10485760 # 10MB
        backupCount: 1
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]